export const ADDRESS_MODULE_NAME = 'ADDRESS_MODULE_NAME'
export const GET_LIST_CITY = 'GET_LIST_CITY'
export const GET_SINGLE_CITY = 'GET_SINGLE_CITY'
export const GET_LIST_DISTRICT = 'GET_LIST_DISTRICT'
export const GET_SINGLE_DISTRICT = 'GET_SINGLE_DISTRICT'
export const GET_LIST_WARD = 'GET_LIST_WARD'
export const GET_SINGLE_WARD = 'GET_SINGLE_WARD'

export const PICK_UP_CITY = 'PICK_UP_CITY'
export const PICK_UP_DISTRICT = 'PICK_UP_DISTRICT'
export const PICK_UP_WARD = 'PICK_UP_WARD'

